### ISSUE TITLE
Fix incomplete logs for react native

### ISSUE THREAD

**Issue by pentatonictritones** [candidelabs/abstractionkit#20]
At the moment, react native does not bubble up the correct errors for this sdk.

Example:[t: bundler eth_estimateUserOperationGas rpc call failed] ["eth_estimateUserOperationGas"]

There is nothing else in the error object.

The sdk should return the full error message, as it does for react web.

**Comment by Sednaoui** [comment]
Pasting the solution that we found in discord chats so others have visibility:

This is a fast fix for this issue, it should transform `AbstractionKitError` to a readable format for react native. Note that `AbstractionKitError` is not exported, an upcoming PR will be made to export it. 

```ts
try{
        // your code here
    }catch(err){
        if (err instanceof AbstractionKitError) {
            throw new Error(
                JSON.stringify({
                    code: err.code,
                    context: err.context,
                    errno: err.errno,
                    message: err.message,
                    cause: err.cause.message,
                })
            );
        } else {
            throw err;
        }
    }
 ```

**Comment by sherifahmed990** [comment]
fixed with:
https://github.com/candidelabs/abstractionkit/commit/ff1854867c72f1e285dd9e7f170dd13f3f447781
https://github.com/candidelabs/abstractionkit/commit/b8c24f69ecbc458bfea5884dfc808ee7b9270912
