### ISSUE TITLE
Passkeys and Webauthn examples timeout on eth_sendUserOperation on experimenal branch with new bundler endpoint (v7) on sepolia

### ISSUE THREAD

**Issue by Sednaoui** [candidelabs/abstractionkit#24]
How to reproduce: 

- Use Passkeys or the Webauthn example
- Use local version of the current experimental branch or the 0.1.12
- Use the new bundler endpoint for (v7)

error received on eth_sendUserOperation: 
```
t: execution timeout at parseStringValue (bigInt:1:25355(175)) at step (<eval>:78:27(38))    in server-side tracer function 'step
```

**Comment by sherifahmed990** [comment]
This has been a bug in the bundler Voltaire, fixed in "StackTop to store one value" https://github.com/candidelabs/voltaire/commit/07c925be9e0af02712b1fa6300a0d88d5853e3ed.
